### ISSUE TITLE
titles: change title defaults

### ISSUE THREAD

**Issue by davidhodge931** [StatisticsNZ/simplevis#152]
Rationale for this change is that simplevis is mainly used not for apps and better defaults would support more insightful quick graphs with less typing

**Comment by davidhodge931** [comment]
Also, for the main title there is the option of making it default to 

1. either NULL 

or

2.
"y_title by x_title" 
"y_title by x_title and col_title"
"y_title by x_title and facet_title" 
"y_title by x_title, col_title and facet_title" 

E.g. in the above example: "Sepal length by sepal width and species"

**Comment by davidhodge931** [comment]
I'm already following the tweaked colnames to some degree in the tooltips that I make with `mutate_text`..   

```
library(simplevis)
library(tidyverse)

df <- iris %>% 
  as_tibble() %>% 
  janitor::clean_names() %>% 
  mutate_text()

p <- ggplot_point_col(df, sepal_width, sepal_length, species, text)

plotly::ggplotly(p, tooltip = "text")
```

**Comment by klee8** [comment]
I like the snakecase >> Sentence case option for visuals also. As the changes are consistent, I don't think that there will be confusion lining up the graph info with the data. Anyone with enough know-how to download the data to play will have enough sense to line these up.

**Comment by davidhodge931** [comment]
Done from version 3.5.0 :)
