### ISSUE TITLE
Similar packages / efforts

### ISSUE THREAD

**Issue by CGMossa** [StatisticsNZ/simplevis#242]
I think it would be nice with a section that points to similar packages. 
Of course this package would have its own selling points, and advantages, and
they can only be highlighted by showing what others contribute.

Start:

```markdown

- [`{ggeasy}` is another package aims to simplify `ggplot2`-patterns](https://github.com/jonocarroll/ggeasy/)

```

**Comment by davidhodge931** [comment]
Hi @CGMossa, thanks for the comment  :)

I am happy to reference packages that have a consistent, simplified framework that do different stuff to my package. 

I know there are a few packages out there that are trying to do similar things to `simplevis`. To date, I think that simplevis has the easiest most logical framework in my head.

I was not aware of `ggeasy` . It looks like that package could work really well with `simplevis`, as they share similar objectives and are providing control over themes which `simplevis` does not support.

I did some testing this morning, and most of the functions work with `simplevis`, although not all... if I can be confident that this package works well with mine. Then I am happy to reference it on the website with an example as to how users can more easily modify themes.

```{r}
library(simplevis)
library(palmerpenguins)
library(ggeasy)

p <- gg_point_col(penguins, 
             x_var = bill_length_mm, 
             y_var = body_mass_g, 
             col_var = species)

p + easy_rotate_x_labels() 
p + easy_remove_legend() 
p + easy_x_axis_labels_size(22) 
p + easy_all_text_color("red") # doesn't work
p + easy_remove_x_axis() 
p + easy_remove_y_axis(what = "ticks")
p + easy_move_legend("bottom")
p + easy_legend_at("left")
p + easy_rotate_legend("horizontal")
labelled::var_label(penguins$species) <- "Penguin\nSpecies"
p + easy_labs() # doesn't work
p + easy_rotate_y_labels(angle = "startatbottom", teach = TRUE)
```

**Comment by CGMossa** [comment]
Thanks for the reply.

I'd like to suggest to keep this issue open, as a tracking issue for co-existing with (for now) `{ggeasy}`.
Second, I'm not affiliated with `{ggeasy}`, but I'll take a stab at the issues you've encountered soon.

Also, I'd actually suggest mentioning projects that have the same goal, but might not necessarily play nicely with `{simplevis}`.
This happens a lot in the Rust world, e.g.
This is taking from `evcxr`: 
> ![image](https://user-images.githubusercontent.com/1063624/124627495-e5a5e700-de7f-11eb-8abd-70538d7ee144.png)

But I'm happy with the welcoming suggestion. This is very nice and neat. I hope this project takes off :D
