### ISSUE TITLE
leaflet_sf: pop-up text bug

### ISSUE THREAD

**Issue by johnForne** [StatisticsNZ/simplevis#266]
Kia ora David
Noticed there is potentially an issue with the leaflet_sf() and leaflet_sf_col() functions. The issue is that when I click on a site the pop-up shows the name of all sites in the dataset - not just the site of interest.

I'm not sure if this is an issue with the data or the function. But don't have a reproducible example other than suggesting that you run clean_data.R (https://gitlabstats-prd/environmental-reporting/nzta-no-2/-/blob/master/eda/clean_data.R) down to line 326 and then run the following... and see what the pop-ups look like

```
# issue note for David re simplevis::
sites_sf %>% 
  head()
# Simple feature collection with 6 features and 1 field
# Geometry type: POINT
# Dimension:     XY
# Bounding box:  xmin: 1750060.1 ymin: 5917106 xmax: 1758969.2 ymax: 5949364
# CRS:           EPSG:2193
# # A tibble: 6 × 2
# site                geometry
# <chr>            <POINT [m]>
#   1 AUC004   (1750060.1 5949364)
# 2 AUC005   (1753095.4 5935106)
# 3 AUC007 (1756064.8 5923934.8)
# 4 AUC008 (1755661.6 5921137.9)
# 5 AUC009 (1756811.3 5919276.3)
# 6 AUC011   (1758969.2 5917106)
sites_sf %>%
  st_transform(4326) %>% 
  leaflet_sf() # This use of leaflet_sf() draws the map ok - but the hover over value seems to display strings for all sites (not just the one clicked on)


sites_sf %>%
  st_transform(4326) %>% 
  leaflet_sf_col(col_var = site) # this use of leaflet_sf_col() draws the map ok - but the hover over also doesn't look so good 
```
The pop-up looks like the following...
![image](https://user-images.githubusercontent.com/62327121/132599060-a0935f17-5e10-403e-8429-956acef7ee17.png)

**Comment by davidhodge931** [comment]
Thanks for this @johnForne 

Bug with `mutate_text` function. Seems to occur when there is only one variable selected. A hack workaround for the time-being is to create an empty column.

```
sites_sf %>%
  mutate(" " = "") %>% 
  leaflet_sf() 
```
