### ISSUE TITLE
y_reorder not working?

### ISSUE THREAD

**Issue by klee8** [StatisticsNZ/simplevis#344]
graph_median_per_site <- function(data, .indicator, .region, .nof_band) {
  
    plot_data <- {{ data }} %>% 
      filter(measurement == "Median", 
             np_id == {{ .indicator }}, 
             region == {{ .region }} ) %>%
      rowwise() %>%
      mutate(name = glue::glue(lake_name, " (", lfenzid, ")")) %>%
      group_by(lake_name) %>%
      mutate(max_lake = max(value)) %>%
      ungroup() %>%
      filter(value == max_lake) %>%
      select(name, value, nof_band) %>%
      filter(nof_band == {{ .nof_band }})
    
    str(plot_data)
    
      gg_hbar_col(plot_data, 
                 x_var = value, 
                 y_var = name,
                 col_var = nof_band,
                 y_reorder = T,
                 title = glue::glue("Median ", .indicator, " values in ", .region, " between 2016-2020")) +
        theme(axis.text.x = element_text(angle = 90))
        
}

indicator <- "NH4N_adj"
state <- read_from_datalake("lake_water_quality/tidy/state.RDS")
region <- "Waikato"
graph_median_per_site(state, indicator, region, "C")

**Comment by davidhodge931** [comment]
I think that this should be done in the data itself  for _col, _facet, and _col_facet functions to avoid confusion, as too difficult given different functions within reorder would need to be supported
