### ISSUE TITLE
hboxplot: x_var should default to NULL

### ISSUE THREAD

**Issue by xaviermiles** [StatisticsNZ/simplevis#395]
Within the gg_boxplot_* functions, y_var is not required input (defaults to NULL) since it is not necessary if _stat="identity"_. 

Within the equivalent gg_hboxplot_* functions, x_var is not specified as "Required input" in the help page (and should not be), but it does not default to NULL. This means that y_var must be a named argument when using _stat="identity"_ and no x_var (which is different to how gg_boxplot_* functions can be used).

**Comment by davidhodge931** [comment]
In gg_hboxplot, x_var should default to NULL

**Comment by davidhodge931** [comment]
Not sure why this works 

library(simplevis)
library(dplyr)
library(palmerpenguins)

plot_data <- penguins %>%
  group_by(species, sex) %>%
  summarise_boxplot_stats(body_mass_g)

outliers <- penguins %>%
  group_by(species, sex) %>%
  summarise_boxplot_outliers(body_mass_g)

size_width <- 0.5
```
gg_hboxplot_col(plot_data,
               xmin_var = min,
               xlower_var = lower,
               xmiddle_var = middle,
               xupper_var = upper,
               xmax_var = max,
               y_var = species,
               col_var = sex,
               size_width = size_width,
               stat = "identity",
               x_title = "Body mass g",
               x_breaks_n = 4,
               col_na_rm = TRUE) 
```

**Comment by davidhodge931** [comment]
R is lazy so it works anyway, but should update

**Comment by xaviermiles** [comment]
You could explicitly check for required inputs using base::missing function

**Comment by davidhodge931** [comment]
Done :)
