### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by zawkzaw** [StatisticsNZ/simplevis#421]
When I installed the package, the following error message was given. Please advise on this.
  
> devtools::install_github("statisticsnz/simplevis")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 53/60
  Rate limit reset at: 2022-03-15 02:13:03 UTC

**Comment by davidhodge931** [comment]
Hi @zawkzaw,
 
Could you try the following and let me know if it works?

`devtools::install_github("StatisticsNZ/simplevis")`

**Comment by zawkzaw** [comment]
Thanks. 
But it still gave out the same error massage as follows:

> devtools::install_github("StatisticsNZ/simplevis")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 51/60
  Rate limit reset at: 2022-03-15 02:13:03 UTC

**Comment by davidhodge931** [comment]
or what about if you use remotes package?

remotes::install_github("StatisticsNZ/simplevis")

**Comment by zawkzaw** [comment]
Hi @davidhodge931 
 I have tried it but the same message.
 
> remotes::install_github("StatisticsNZ/simplevis")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
  Rate limit remaining: 49/60
  Rate limit reset at: 2022-03-15 02:13:03 UTC

**Comment by davidhodge931** [comment]
I'm not sure why that error is coming up. 

Maybe just install from CRAN instead?

**Comment by zawkzaw** [comment]
Many thanks for your time.  I will try it.

**Comment by zawkzaw** [comment]
Hi @davidhodge931 
Finally I made it to install your wonderful package from CRAN.
Thank you.
