### ISSUE TITLE
y_reorder not working in all cases.

### ISSUE THREAD

**Issue by klee8** [StatisticsNZ/simplevis#437]
y_reorder works in most cases, but found a few examples where it did not e.g. 
![image](https://user-images.githubusercontent.com/9483236/160486335-c1e4e91b-ec4d-485e-9e4e-3ab0eba95cd0.png)

where most of the other plots were correct...

```
  plot <-  gg_hbar(plot_data,
                   x_var = value,
                   y_var = lake_name,
                   y_labels = ggplot2::waiver(),
                   y_reorder = TRUE,
                   y_title = "",
                   x_title = .xtitle,
                   title = .title,
                   title_wrap = 50,
                   theme = .theme,
                   mobile = .mobile)
```

**Comment by davidhodge931** [comment]
Hi Kate, oh that's weird.

Is y_var a factor? Can you print the plot_data out, or provide some data to illustrate the problem?

**Comment by klee8** [comment]
Ah, got it. "For a categorical y variable" in the doc means "Factorised".  I have changed y_var to a factor (previously character) and left x_var as a double. It works in all cases now. Thanks David!

**Comment by klee8** [comment]
Hey David, sorry for the false alarm. It is happening where the lake has more than one value. It seems to have added them. I'll go sort it out at the data level.

Does it actually make a difference if the y_var is a factor? In the documentation it only says 'categorical  variable' not that it needs to be factorised, or maybe those things are synonymous for you?

**Comment by davidhodge931** [comment]
Oh great! 

No, It shouldn't matter if y_var is a factor. Why just trying to brainstorm why it could be happening

If it says categorical, it means character/factor/logical

**Comment by klee8** [comment]
Sweet as. Thanks for your help!
