### ISSUE TITLE
ggplot_line_facet: make y scale prettier when all y_var values are zero

### ISSUE THREAD

**Issue by johnForne** [StatisticsNZ/simplevis#59]
Kia ora Dave
This is the second time I've been tripped up by this and I've not found the error message about y_breaks not found unhelpful.

For some reason ggplot_line_facet seems to be unable to plot a vector where all the values are zero. I prefer how geom_line handles such data (see below).

Any chance you can resolve this?

Thanks

```
library(dplyr)

plot_data <- storms %>%
  mutate(status = stringr::str_to_sentence(status)) %>%
  group_by(year, status) %>%
  summarise(wind = round(mean(wind), 2)) 

plot <- plot_data %>%
  ggplot_line_facet(data = , x_var = year, y_var = wind, facet_var = status)

plot

plot <- plot_data %>%
  mutate(wind = 0) %>% 
  ggplot_line_facet(data = , x_var = year, y_var = wind, facet_var = status)
#Error in ggplot_line_facet(., data = , x_var = year, y_var = wind, facet_var = status) : 
  object 'y_breaks' not found

plot

plot <- plot_data %>%
  mutate(wind = 0) %>% 
  ggplot() +
  geom_line(aes(x = year, y = wind)) +
  facet_wrap(~ status)

plot
```

**Comment by davidhodge931** [comment]
It plots it but with a y axis of [0, -1]

Better if it was [0, 1]

**Comment by davidhodge931** [comment]
From version 2.7.8, will look like this @johnForne 
![image](https://user-images.githubusercontent.com/55065152/116622243-7ea81580-a998-11eb-8874-34e710d3c78b.png)
