### ISSUE TITLE
 increase y axis in App

### ISSUE THREAD

**Issue by klee8** [StatisticsNZ/simplevis#60]
The lines and points are cut in half at the top and bottom of the graph for some time series e.g. Artificial landcover, artificial bare surfaces, transport infrastructure, Marlborough.

It might help to increase the y axis at the top and bottom by a little. 

Dave's notes:

The y axis breaks are selected by the simplevis function using the pretty algrorithm, and making no gap beween the x axis so that it looks good

But when the bottom/top break is the same as the bottom/top value, it doesn't look very good

![Capture](https://user-images.githubusercontent.com/9483236/107890310-0a56fc00-6f7d-11eb-97d5-de5ff82d7ea7.JPG)

**Comment by davidhodge931** [comment]
For specific graphs, user can use y_expand argument if necessary to expand both sides

This is mainly a ggplotly problem, as the same graph in ggplot looks fine. 

So will wait, and hopefully plotly will address this
